name: mall_demo
description: Flutter实战

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

#生产环境
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  #  网络请求库
  dio: ^2.1.7
  #  图片轮播
  flutter_swiper: ^1.1.6
  #  屏幕适配
  flutter_screenutil: ^0.5.2
  #  启动URL的插件
  url_launcher: ^5.0.3
  #  上拉加载
  flutter_easyrefresh: ^1.2.7
  #  状态管理
  provide: ^1.0.2
  #  toast 插件
  fluttertoast: ^3.1.0
  #  路由
  fluro: "^1.5.0"
  #  webview
  flutter_html: ^0.10.3
  #  数据持久化
  shared_preferences: ^0.5.3

#开发环境   上线时不会被打包进去
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
